apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-inferencing
  labels:
    app: ml-inferencing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-inferencing
  template:
    metadata:
      labels:
        app: ml-inferencing
    spec:
      containers:
      - name: ml-inferencing
        image: ${ACR_NAME}.azurecr.io/ml/inferencing:latest
        ports:
        - containerPort: 80
