apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-training
  labels:
    app: ml-training
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-training
  template:
    metadata:
      labels:
        app: ml-training
    spec:
      containers:
      - name: ml-training
        image: ${ACR_NAME}.azurecr.io/ml/training:latest
        ports:
        - containerPort: 80
