apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-training-base
  labels:
    app: ml-training-base
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-training-base
  template:
    metadata:
      labels:
        app: ml-training-base
    spec:
      containers:
      - name: ml-training-base
        image: ${ACR_NAME}.azurecr.io/ml/training/base:latest
        ports:
        - containerPort: 80
